name: "Deploy AWS EC2 - Prod"

on:
  push:
    branches: [main]
    paths: ["infra/aws-ec2/**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  prod:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra/aws-ec2
      environment: prod
      project_name: incident-commander
      service_name: aws-ec2
    secrets: inherit
